version: '3.8'

services:
    app:
        build: 
            dockerfile: Dockerfile
            context: .
        ports:
            - 9000:9000
        volumes:
            - ./:/app
        restart: unless-stopped
#comment to remember that this database its not attached to any volume
    database_service:
        image: postgres
        restart: always
        hostname: postgree_hostname
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=test
        ports:
            - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql