version: '3.8'

services:
    # app:
    #     build: 
    #         dockerfile: Dockerfile
    #         context: .
    #     ports:
    #         - 9000:9000
    #     volumes:
    #         - ./:/app
    #     restart: unless-stopped
    postgres:
        image: postgres
        hostname: postgree_hostname
        environment:
            - POSTGRES_USER=test
            - POSTGRES_PASSWORD=test
            - POSTGRES_DB=test
        ports:
            - 5555:5432
        volumes:
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
        # tmpfs:
        #     - /var/lib/postgresql/data
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5